name: CI devops 2024
on:
  push:
    branches:
      
main
develop
pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
      # Updated checkout action to v3
      
uses: actions/checkout@v3

      
name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'  # Specify the distribution to fix the error

      
name: Build and test with Maven
      run: mvn clean verify --file ./simple-api/pom.xml